FROM golang:1.26.4

WORKDIR /app/backend

ENV GOMODCACHE=/gomod-cache
ENV GOCACHE=/go-cache
ENV GOFLAGS=-mod=mod

RUN go env -w GOCACHE=${GOCACHE} \
  && go env -w GOMODCACHE=${GOMODCACHE} \
  && go env -w GOFLAGS=${GOFLAGS} \
  && apt-get update \
  && apt-get install -y --no-install-recommends libwebp-dev ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY --chmod=755 services/backend/go.mod /app/backend/go.mod
COPY --chmod=755 services/backend/go.sum /app/backend/go.sum

RUN --mount=type=cache,target=${GOMODCACHE} \
  --mount=type=cache,target=${GOCACHE} \
  go install gotest.tools/gotestsum@latest \
  && go install github.com/swaggo/swag/cmd/swag@latest

RUN --mount=type=cache,target=${GOMODCACHE} \
  --mount=type=cache,target=${GOCACHE} \
  go mod download

