FROM golang:1.26.3 AS basebuilder
WORKDIR /app/backend

ENV GOMODCACHE=/gomod-cache
ENV GOCACHE=/go-cache

RUN go env -w GOCACHE=${GOCACHE}
RUN go env -w GOMODCACHE=${GOMODCACHE}
RUN go env -w GOFLAGS=-mod=mod

# Install WebP development libraries for CGO
RUN apt-get update && apt-get install -y libwebp-dev

COPY --chmod=755 services/backend/go.mod /app/backend/go.mod
COPY --chmod=755 services/backend/go.sum /app/backend/go.sum

RUN --mount=type=cache,target=${GOCACHE} go install golang.org/x/tools/cmd/goimports@latest
RUN --mount=type=cache,target=${GOCACHE} go install github.com/swaggo/swag/cmd/swag@latest
RUN --mount=type=cache,target=${GOCACHE} go install github.com/cortesi/modd/cmd/modd@latest
RUN --mount=type=cache,target=${GOCACHE} go install github.com/maruel/panicparse/v2/cmd/pp@latest

# install dependencies
RUN --mount=type=cache,target=${GOMODCACHE} --mount=type=cache,target=/root/.config/go \
    go mod download