ls: 
  services/backend:
    .go: snake_case
    .sql: snake_case
  services/frontend:
    .js: kebab-case
    .ts: kebab-case
    # .svelte: kebab-case
    .sass: kebab-case
    .scss: kebab-case
    .css: kebab-case
    .d.ts: kebab-case

ignore: 
  - .git
  - services/backend/src/helper/eakte
  - services/frontend/node_modules
  - services/frontend/.svelte-kit
