version: "2"
run:
  tests: false
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - gocyclo
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - grouper
    - iface
    - importas
    - interfacebloat
    - intrange
    - maintidx
    - makezero
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - reassign
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
  settings:
    varnamelen:
      ignore-decls:
        - tx *sqlx.Tx
        - t testing.T
        - f *foo.Bar
        - T any
        - errMsg string
        - c *fiber.Ctx
        - db *sqlx.DB
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
