services:
  imapserver:
    image: tabascoterrier/docker-imap-devel:latest
    environment:
      # Create a default mailbox and credentials for local development/testing
      MAIL_ADDRESS: "address@example.org"
      MAIL_PASS: "pass"
      MAILNAME: "localdomain.test"
    networks:
      - intranet
    hostname: imap-server
    ports:
      - "10025:25"
      - "993:993"
