services:
  kafka:
    image: lensesio/fast-data-dev:3.9.0
    hostname: kafka
    environment:
      ADV_HOST: kafka
      RUNNING_SAMPLEDATA:
      RUNTESTS: 0
      KAFKA_LISTENERS: PLAINTEXT://:9092,DOCKERCOMPOSE://:19092,CONTROLLER://:16062
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKERCOMPOSE://demo-kafka:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        DOCKERCOMPOSE:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,
        SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      DISABLE: debezium-mongodb,debezium-mysql,debezium-postgres,debezium-sqlserver,debezium-jdbc
    ports:
      - 9092:9092
      - 8081:8081
      - 8083:8083
      - 3030:3030
    volumes:
      - kafka_data:/data
    networks:
      - intranet

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kafka-ui.rule=(Host(`kafka.nextreleaseplease.com`)&&PathPrefix(`/`))"
      - "traefik.http.routers.kafka-ui.priority=1"
      - "traefik.http.routers.kafka-ui.service=kafka-ui"
      - "traefik.http.services.kafka-ui.loadbalancer.server.port=8080"
      - "traefik.http.routers.kafka-ui.entrypoints=web,web-secure"
    volumes:
      - ./kafka/kafka-ui/dynamic_config.yaml:/etc/kafkaui/dynamic_config.yaml
    ports:
      - 8020:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      kafka:
        condition: service_started

volumes:
  kafka_data:
    driver: local
