---
networks:
  intranet:
    internal: false
    driver: bridge

services:
  clamav:
    image: ghcr.io/dcssoftware/dcs-claimav-wrapper:sha-50fd72c
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - 33779:33779
    healthcheck:
      test:
        ["CMD", "sh", "-c", "echo 'PING' | nc -w 5 localhost 3310 | grep PONG"]
      interval: 10s
      timeout: 2s
      retries: 15
      start_period: 10s
    networks:
      - intranet
