---
networks:
  intranet:
    internal: false
    driver: bridge

services:
  cypress:
    image: cypress/included:15.13.0
    platform: linux/amd64
    command: run --browser chrome --headless
    networks:
      - intranet
