package customerrorconst

type ErrorIdentifier string

const (
	ERROR_IDENTIFIER_BAD_REQUEST      ErrorIdentifier = "BAD_REQUEST"
	ERROR_IDENTIFIER_VALIDATION_ERROR ErrorIdentifier = "DATA_VALIDATION_ERROR"

	ERROR_IDENTIFIER_UNAUTHORIZED                     ErrorIdentifier = "USER_UNAUTHORIZED"
	ERROR_IDENTIFIER_DATABASE_NOT_FOUND               ErrorIdentifier = "DATABASE_NOT_FOUND_ERROR"
	ERROR_IDENTIFIER_DATABASE_TRANSACTION_NOT_STARTED ErrorIdentifier = "DATABASE_TRANSACTION_NOT_STARTED_ERROR"
	ERROR_IDENTIFIER_DATABASE_TRANSACTION_NO_COMMIT   ErrorIdentifier = "DATABASE_TRANSACTION_NO_COMMIT_ERROR"
	ERROR_IDENTIFIER_DATABASE_TRANSACTION_NO_ROLLBACK ErrorIdentifier = "DATABASE_TRANSACTION_NO_ROLLBACK_ERROR"
	ERROR_IDENTIFIER_DATABASE_CONFLICT                ErrorIdentifier = "DATABASE_RESOURCE_CONFLICT"
	ERROR_IDENTIFIER_DATABASE                         ErrorIdentifier = "DATABASE_ERROR"
	ERROR_IDENTIFIER_INTERNAL_SERVER_ERROR            ErrorIdentifier = "INTERNAL_SERVER_ERROR"
	ERROR_IDENTIFIER_S3_NOT_FOUND                     ErrorIdentifier = "S3BUCKET_NOT_FOUND_ERROR"
	ERROR_IDENTIFIER_S3_NOT_DELETED                   ErrorIdentifier = "S3BUCKET_NOT_DELETED_ERROR"
	ERROR_IDENTIFIER_S3_NOT_UPLOADED                  ErrorIdentifier = "S3BUCKET_NOT_UPLOADED_ERROR"
	ERROR_IDENTIFIER_S3_DOWNLOAD_FAILED               ErrorIdentifier = "S3BUCKET_DOWNLOAD_FAILED_ERROR"
	ERROR_IDENTIFIER_AI_NO_RESPONSE                   ErrorIdentifier = "AI_NO_RESPONSE_ERROR"
	ERROR_IDENTIFIER_APPLICATION_ALREADY_PROCESSED    ErrorIdentifier = "APPLICATION_ALREADY_PROCESSED_ERROR"
)
