package xdomeaconsts

type DatenTyp string

const (
	Daten_Typ_AnyURI             DatenTyp = "001"
	Daten_Typ_Base64Binary       DatenTyp = "002"
	Daten_Typ_Boolean            DatenTyp = "003"
	Daten_Typ_Byte               DatenTyp = "004"
	Daten_Typ_Date               DatenTyp = "005"
	Daten_Typ_DateTime           DatenTyp = "006"
	Daten_Typ_Decimal            DatenTyp = "007"
	Daten_Typ_Double             DatenTyp = "008"
	Daten_Typ_Duration           DatenTyp = "009"
	Daten_Typ_ENTITIES           DatenTyp = "010"
	Daten_Typ_ENTITY             DatenTyp = "011"
	Daten_Typ_Float              DatenTyp = "012"
	Daten_Typ_GDay               DatenTyp = "013"
	Daten_Typ_GMonth             DatenTyp = "014"
	Daten_Typ_GMonthDay          DatenTyp = "015"
	Daten_Typ_GYear              DatenTyp = "016"
	Daten_Typ_GYearMonth         DatenTyp = "017"
	Daten_Typ_HexBinary          DatenTyp = "018"
	Daten_Typ_ID                 DatenTyp = "019"
	Daten_Typ_IDREF              DatenTyp = "020"
	Daten_Typ_IDREFS             DatenTyp = "021"
	Daten_Typ_Int                DatenTyp = "022"
	Daten_Typ_Integer            DatenTyp = "023"
	Daten_Typ_Language           DatenTyp = "024"
	Daten_Typ_Long               DatenTyp = "025"
	Daten_Typ_Name               DatenTyp = "026"
	Daten_Typ_NCNAME             DatenTyp = "027"
	Daten_Typ_NegativeInteger    DatenTyp = "028"
	Daten_Typ_NMTOKEN            DatenTyp = "029"
	Daten_Typ_NMTOKENS           DatenTyp = "030"
	Daten_Typ_NonNegativeInteger DatenTyp = "031"
	Daten_Typ_NonPositiveInteger DatenTyp = "032"
	Daten_Typ_NormalizedString   DatenTyp = "033"
	Daten_Typ_NOTATION           DatenTyp = "034"
	Daten_Typ_PositiveInteger    DatenTyp = "035"
	Daten_Typ_QName              DatenTyp = "036"
	Daten_Typ_Short              DatenTyp = "037"
	Daten_Typ_String             DatenTyp = "038"
	Daten_Typ_Time               DatenTyp = "039"
	Daten_Typ_Token              DatenTyp = "040"
	Daten_Typ_UnsignedByte       DatenTyp = "041"
	Daten_Typ_UnsignedInt        DatenTyp = "042"
	Daten_Typ_UnsignedLong       DatenTyp = "043"
	Daten_Typ_UnsignedShort      DatenTyp = "044"
	Daten_Typ_AnySimpleType      DatenTyp = "045"
)
